# Technical Indicators
technical_indicators:
  - SMA
  - EMA
  - RSI
  - MACD
  - Bollinger Bands

# Time-based features
time_features:
  - hour
  - day_of_week
  - is_weekend

# Feature selection
feature_selection:
  method: 'correlation'
  threshold: 0.8

# Normalization
normalization:
  method: 'min_max'
  feature_range: [-1, 1]